### ISSUE TITLE
Expose X-akismet-pro-tip

### ISSUE THREAD

**Issue by nijel** [ubernostrum/akismet#5]
From the [docs](https://akismet.com/development/api/#comment-check):

> If the `X-akismet-pro-tip` header is set to `discard`, then Akismet has determined that the comment is blatant spam, and you can safely discard it without saving it in any spam queue. Read more about this feature in this [Akismet blog post](https://blog.akismet.com/2014/04/23/theres-a-ninja-in-your-akismet/).

It would be useful to have access to this flag.

**Comment by ubernostrum** [comment]
The crucial question here is how to expose this given the existing API of the module -- there's no obvious extra channel for it to return this information right now.

**Comment by nijel** [comment]
Meanwhile, I've switched to a different module which has this: https://github.com/Nekmo/python-akismet/blob/3c6d0f4e24ddeeb0a40ea76ff4e89c866bad03c3/akismet/__init__.py#L23-L27. It still works as a boolean condition, but the truthy values have additional information.

**Comment by ubernostrum** [comment]
The issue there, though, is that it would be a backwards-incompatible change to the API of this module to change to doing something like that. I’d prefer to avoid backwards incompatible changes if possible, or only make that change if I have reason to be making other incompatible changes at the same time.

**Comment by ubernostrum** [comment]
The most recent commits I've pushed, which will become version 1.3 once I finalize some API choices, now expose the "discard" value through a new API.
